
CREATE TABLE `credential` (
	`credential_id` INTEGER(11) NOT NULL AUTO_INCREMENT, 
	`type` VARCHAR(20), 
	`url` VARCHAR(50), 
	`created` VARCHAR(50), 
	`modified` VARCHAR(50), 
	`name` VARCHAR(50), 
	`description` VARCHAR(100), 
	`organization_id` INTEGER(11), 
	`credential_type` INTEGER(11), 
	PRIMARY KEY  `(credential_id`) 
)DEFAULT CHARSET=utf8mb4 ENGINE=InnoDB


CREATE TABLE `host` (
	`host_id` INTEGER(11) NOT NULL AUTO_INCREMENT, 
	`type` VARCHAR(20), 
	`url` VARCHAR(50), 
	`created` VARCHAR(50), 
	`modified` VARCHAR(50), 
	`name` VARCHAR(50), 
	`description` VARCHAR(100), 
	`inventory_id` INTEGER(11), 
	`enabled` TINYINT(1), 
	`instance_id` INTEGER(11), 
	`variables` LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin, 
	`last_job` INTEGER(11), 
	`last_job_host_summary` INTEGER(11), 
	`ansible_facts_modified` VARCHAR(100), 
	PRIMARY KEY  `(host_id`) 
)DEFAULT CHARSET=utf8mb4 ENGINE=InnoDB


CREATE TABLE `instance` (
	`instance_id` INTEGER(11) NOT NULL AUTO_INCREMENT, 
	`type` VARCHAR(20), 
	`url` VARCHAR(50), 
	`uuid` VARCHAR(100), 
	`hostname` VARCHAR(50), 
	`created` VARCHAR(50), 
	`modified` VARCHAR(50), 
	`capacity_adjustment` DECIMAL(10, 0), 
	`version` VARCHAR(20), 
	`capacity` INTEGER(11), 
	`jobs_running` INTEGER(11), 
	`jobs_total` INTEGER(11), 
	`cpu` INTEGER(11), 
	`memory` INTEGER(11), 
	`cpu_capacity` INTEGER(11), 
	`mem_capacity` INTEGER(11), 
	`enabled` TINYINT(1), 
	`managed_by_policy` TINYINT(1), 
	PRIMARY KEY  `(instance_id`) 
)DEFAULT CHARSET=utf8mb4 ENGINE=InnoDB


CREATE TABLE `inventory` (
	`inventory_id` INTEGER(11) NOT NULL AUTO_INCREMENT, 
	`type` VARCHAR(20), 
	`url` VARCHAR(50), 
	`created` VARCHAR(50), 
	`modified` VARCHAR(50), 
	`name` VARCHAR(50) NOT NULL, 
	`description` VARCHAR(100), 
	`organization_id` INTEGER(11), 
	`kind` VARCHAR(10), 
	`host_filter` VARCHAR(100), 
	`variables` LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin, 
	`has_active_failures` TINYINT(1), 
	`total_hosts` INTEGER(11), 
	`hosts_with_active_failures` INTEGER(11), 
	`total_groups` INTEGER(11), 
	`has_inventory_sources` TINYINT(1), 
	`total_inventory_sources` INTEGER(11), 
	`inventory_sources_with_failures` INTEGER(11), 
	PRIMARY KEY  `(inventory_id`) 
)DEFAULT CHARSET=utf8mb4 ENGINE=InnoDB


CREATE TABLE `job` (
	`job_id` INTEGER(11) NOT NULL AUTO_INCREMENT, 
	`type` VARCHAR(20), 
	`url` VARCHAR(50), 
	`created` VARCHAR(50), 
	`modified` VARCHAR(50), 
	`name` VARCHAR(50), 
	`description` VARCHAR(100), 
	`unified_job_template` INTEGER(11), 
	`launch_type` VARCHAR(50), 
	`status` VARCHAR(20), 
	`failed` TINYINT(1), 
	`started` VARCHAR(50), 
	`finished` VARCHAR(50), 
	`canceled_on` VARCHAR(50), 
	`elapsed` DECIMAL(10, 0), 
	`job_explanation` VARCHAR(100), 
	`execution_node` VARCHAR(20), 
	`controller_node` VARCHAR(20), 
	`job_type` VARCHAR(10), 
	`inventory_id` INTEGER(11), 
	`project` INTEGER(11), 
	`playbook` VARCHAR(50), 
	`scm_branch` VARCHAR(50), 
	`forks` INTEGER(11), 
	`limit` VARCHAR(50), 
	`verbosity` INTEGER(11), 
	`extra_vars` LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin, 
	`job_tags` VARCHAR(50), 
	`force_handlers` TINYINT(1), 
	`skip_tags` VARCHAR(50), 
	`start_at_task` VARCHAR(50), 
	`timeout` INTEGER(11), 
	`use_fact_cache` TINYINT(1), 
	`organization_id` INTEGER(11), 
	`job_template_id` INTEGER(11), 
	PRIMARY KEY  `(job_id`) 
)DEFAULT CHARSET=utf8mb4 ENGINE=InnoDB


CREATE TABLE `job_template` (
	`job_template_id` INTEGER(11) NOT NULL AUTO_INCREMENT, 
	`type` VARCHAR(20), 
	`url` VARCHAR(50), 
	`created` VARCHAR(50), 
	`modified` VARCHAR(50), 
	`name` VARCHAR(50), 
	`description` VARCHAR(100), 
	`job_type` VARCHAR(10), 
	`inventory_id` INTEGER(11), 
	`project_id` INTEGER(11), 
	`playbook` VARCHAR(50), 
	`scm_branch` VARCHAR(50), 
	`forks` INTEGER(11), 
	`limit` VARCHAR(50), 
	`verbosity` VARCHAR(20), 
	`extra_vars` LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin, 
	`job_tags` VARCHAR(20), 
	`force_handlers` TINYINT(1), 
	`skip_tags` VARCHAR(20), 
	`start_at_task` VARCHAR(20), 
	`timeout` INTEGER(11), 
	`use_fact_cache` TINYINT(1), 
	`organization_id` INTEGER(11), 
	`last_job_run` VARCHAR(50), 
	`last_job_failed` TINYINT(1), 
	`next_job_run` VARCHAR(100), 
	`status` VARCHAR(20), 
	`host_config_key` VARCHAR(100), 
	`ask_scm_branch_on_launch` TINYINT(1), 
	`ask_diff_mode_on_launch` TINYINT(1), 
	`ask_variables_on_launch` TINYINT(1), 
	`ask_limit_on_launch` TINYINT(1), 
	`ask_tags_on_launch` TINYINT(1), 
	`ask_skip_tags_on_launch` TINYINT(1), 
	`ask_job_type_on_launch` TINYINT(1), 
	`ask_verbosity_on_launch` TINYINT(1), 
	`ask_inventory_on_launch` TINYINT(1), 
	`ask_credential_on_launch` TINYINT(1), 
	`survey_enabled` TINYINT(1), 
	`become_enabled` TINYINT(1), 
	`diff_mode` TINYINT(1), 
	`allow_simultaneous` TINYINT(1), 
	`custom_virtualenv` VARCHAR(100), 
	`job_slice_count` INTEGER(11), 
	`webhook_service` VARCHAR(20), 
	`webhook_credential` INTEGER(11), 
	PRIMARY KEY  `(job_template_id`) 
)DEFAULT CHARSET=utf8mb4 ENGINE=InnoDB


CREATE TABLE `project` (
	`project_id` INTEGER(11) NOT NULL AUTO_INCREMENT, 
	`type` VARCHAR(20), 
	`url` VARCHAR(50), 
	`created` VARCHAR(50), 
	`modified` VARCHAR(50), 
	`name` VARCHAR(50), 
	`description` VARCHAR(100), 
	`local_path` VARCHAR(100), 
	`scm_type` VARCHAR(20), 
	`scm_url` VARCHAR(100), 
	`scm_branch` VARCHAR(50), 
	`scm_refspec` VARCHAR(100), 
	`scm_clean` TINYINT(1), 
	`scm_delete_on_update` TINYINT(1), 
	`credential_id` INTEGER(11), 
	`timeout` INTEGER(11), 
	`scm_revision` VARCHAR(100), 
	`last_job_run` VARCHAR(100), 
	`last_job_failed` TINYINT(1), 
	`next_job_run` VARCHAR(100), 
	`status` VARCHAR(20), 
	`organization_id` INTEGER(11), 
	`scm_update_on_launch` TINYINT(1), 
	`scm_update_cache_timeout` INTEGER(11), 
	`allow_override` TINYINT(1), 
	`custom_virtualenv` VARCHAR(50), 
	`last_update_failed` TINYINT(1), 
	`last_updated` VARCHAR(100), 
	PRIMARY KEY  `(project_id`) 
)DEFAULT CHARSET=utf8mb4 ENGINE=InnoDB


CREATE TABLE `workflow_job_template` (
	`workflow_job_template_id` INTEGER(11) NOT NULL AUTO_INCREMENT, 
	`type` VARCHAR(20), 
	`url` VARCHAR(50), 
	`created` VARCHAR(50), 
	`modified` VARCHAR(50), 
	`name` VARCHAR(50), 
	`description` VARCHAR(100), 
	`last_job_run` VARCHAR(50), 
	`last_job_failed` TINYINT(1), 
	`next_job_run` VARCHAR(50), 
	`status` VARCHAR(20), 
	`extra_vars` LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin, 
	`organization_id` INTEGER(11), 
	`survey_enabled` TINYINT(1), 
	`allow_simultaneous` TINYINT(1), 
	`ask_variables_on_launch` TINYINT(1), 
	`inventory_id` INTEGER(11), 
	`limit` VARCHAR(100), 
	`scm_branch` VARCHAR(100), 
	`ask_inventory_on_launch` TINYINT(1), 
	`ask_scm_branch_on_launch` TINYINT(1), 
	`ask_limit_on_launch` TINYINT(1), 
	`webhook_service` VARCHAR(10), 
	`webhook_credential` INTEGER(11), 
	PRIMARY KEY  `(workflow_job_template_id`) 
)DEFAULT CHARSET=utf8mb4 ENGINE=InnoDB

