version: '1'
services:
  # 其他配置参考 https://hub.docker.com/r/tiangolo/uvicorn-gunicorn-fastapi/
  backend:
    build: .
    volumes:
      - "./backend/upload:/backend/upload"
      - "./backend/amisadmin.db:/backend/amisadmin.db"
    ports:
      - "8000:8000"
    env_file:
      - "backend/.env"
    environment:
      - APP_MODULE=backend.main:app