version: "3"

services:
  CapricornusNG:
    image: "jointhero/capricornusng:latest"
    container_name: capricornusng
    hostname: capricornusng
    restart: on-failure
    environment:
      LANG: "zh_CN"
      LANGUAGE: "zh_CN"
    ports:
      - "8880:8880/tcp"
      - "8843:8843/tcp"
    healthcheck:
        test: ["CMD", "netstat", "-anp", "|", "grep 8880", "||", "exit 1"]
        interval: 30s
        timeout: 5s
        retries: 5
    networks:
      - capricornusng
networks:
  capricornusng:
    driver: bridge
